title: Machine Learning for Detection of Pediatric Otitis
description: Slides on the research done in TM Helectronic Medical Records presented to the HLP Lab at the University of Pennsylvania to start collaborating with them.
